name: Build app for macOS and add to release

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install npm dependencies
      run: npm install
    - name: Build for mac
      run: npm run build:mac
    - name: Upload to a release
      uses: fnkr/github-action-ghr@v1.2
      env:
        GHR_PATH: dist/quick-start-macOS.zip
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
